apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
  namespace: dev
  label:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 2
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: wil42/playground
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
